#!/bin/bash
if [ ! $1 ] || [ ! $2 ]; then
  echo "USAGE dev-server-setup user host"
  exit 1
fi

echo "--- Setting up server"
ssh $1@$2 <<'SUDOSCRIPT'
echo "Installing"
sudo apt-get update
sudo apt-get-y upgrade
sudo apt-get install -y ufw wget mosh git zsh apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common make build-essential zlib1g-dev autoconf bison libffi-dev libc-dev libyaml-dev libgdbm-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev ack tmux ruby vim universal-ctags keychain

echo "--- General server setup"
export HOSTNAME=$2
sudo hostnamectl set-hostname $HOSTNAME
sudo mkdir /etc/environment.d
sudo echo "HOSTNAME=`echo $HOSTNAME`" > /etc/environment.d/99-hostname
sudo timedatectl set-timezone Europe/London

echo "--- UFW and SSH setup"
sudo ufw allow 22/tcp
sudo ufw allow 3000:3010/tcp
sudo ufw allow 2022/tcp
sudo ufw allow 60000:61000/udp
sudo ufw --force enable
sudo sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
sudo sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
sudo sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
sudo sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
sudo sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding yes/' /etc/ssh/sshd_config
sudo sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding yes/' /etc/ssh/sshd_config
sudo sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
sudo service sshd restart

echo "--- Install Docker"
sudo mkdir -m 0755 -p /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --dearmor -o /etc/apt/keyrings/docker.gpg
sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get -y update
sudo apt-cache policy docker-ce
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

echo "--- Install github"
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
sudo apt-get update -y
sudo apt-get install -y gh

echo "--- Install Eternal Terminal"
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:jgmath2000/et
sudo apt-get update
sudo apt-get install et

echo "--- Set up dev user"
sudo mkdir -p /etc/skel/.ssh
sudo cp ~/.ssh/authorized_keys /etc/skel/.ssh
sudo adduser --disabled-password --gecos "" dev
sudo usermod -aG sudo dev
sudo usermod -aG docker dev
sudo echo "dev ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
sudo chsh -s /usr/bin/zsh dev
sudo mkdir -p /home/dev/.ssh
sudo cp ~/.ssh/authorized_keys /home/dev/.ssh
sudo chown dev /home/dev/.ssh
sudo chown dev /home/dev/.ssh/*
SUDOSCRIPT

echo "- Installing for dev user"

echo "- Copying bin folder"
rsync -azP ~/bin/ dev@$2:~/bin

echo "- Setting up dev"
ssh dev@$2 <<'DEVSCRIPT'
ln -nfs ~/bin/oh-my-zsh ~/.oh-my-zsh
ln -nfs ~/bin/zshrc ~/.zshrc
ln -nfs ~/bin/aws ~/.aws
ln -nfs ~/bin/tmux.conf ~/.tmux.conf
ln -nfs ~/bin/echodek.db002 ~/.echodek.db002
ln -nfs ~/bin/echodek.db003 ~/.echodek.db003
ln -nfs ~/bin/erb-lint.yml ~/.erb-lint.yml
ln -nfs ~/bin/erb-lint_rubocop.yml ~/.erb-lint_rubocop.yml

echo "--- Installing rbenv"
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
DEVSCRIPT

echo "--- Now run:"
echo "rbenv install 3.1.2"
echo "gem install erb_lint standardrb"
ssh dev@$2
