version: "3.9"

services:
  memcached:
    image: memcached:latest
  redis_db:
    image: redis:alpine
  mysql_db:
    image: mysql:latest
    volumes:
      - mysql_db:/var/lib/mysql
      - ./utf8.cnf:/etc/mysql/mysql.conf.d/utf8.cnf
    environment:
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
      MYSQL_ROOT_PASSWORD: "root"
volumes:
  mysql_db:
